apiVersion: v1
kind: Namespace
metadata:
  name: nutritiontrax

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: nutritiontrax
data:
  init.sql: |
    CREATE DATABASE nutrition_dev;

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-schema
  namespace: nutritiontrax
data:
  schema.sql: |
    SET statement_timeout = 0;
    SET lock_timeout = 0;
    SET idle_in_transaction_session_timeout = 0;
    SET transaction_timeout = 0;
    SET client_encoding = 'UTF8';
    SET standard_conforming_strings = on;
    SELECT pg_catalog.set_config('search_path', '', false);
    SET check_function_bodies = false;
    SET xmloption = content;
    SET client_min_messages = warning;
    SET row_security = off;

    SET default_tablespace = '';
    SET default_table_access_method = heap;

    CREATE TABLE public.exercises (
        exercise_id integer NOT NULL,
        exercise_type character varying(100) NOT NULL,
        calories_per_kg numeric(5,2) NOT NULL
    );

    ALTER TABLE public.exercises ALTER COLUMN exercise_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.exercises_exercise_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    CREATE TABLE public.food (
        food_id integer NOT NULL,
        description character varying(255) NOT NULL,
        calories numeric(8,2),
        protein numeric(6,2),
        carbs numeric(6,2),
        total_fat numeric(6,2),
        saturated_fat numeric(6,2),
        cholesterol numeric(6,2),
        sodium numeric(6,2),
        sugar numeric(6,2)
    );

    ALTER TABLE public.food ALTER COLUMN food_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.food_food_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    CREATE TABLE public.goals (
        goal_id integer NOT NULL,
        user_id integer NOT NULL,
        goal_type character varying(50) NOT NULL,
        date_added timestamp without time zone DEFAULT now(),
        goal_end_date date,
        goal_complete boolean DEFAULT false
    );

    ALTER TABLE public.goals ALTER COLUMN goal_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.goals_goal_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    CREATE TABLE public.meal_foods (
        meal_id integer NOT NULL,
        food_id integer NOT NULL,
        food_amount numeric(8,2) NOT NULL
    );

    CREATE TABLE public.meals (
        meal_id integer NOT NULL,
        user_id integer NOT NULL,
        meal_date timestamp without time zone DEFAULT now()
    );

    ALTER TABLE public.meals ALTER COLUMN meal_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.meals_meal_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    CREATE TABLE public.progress_tracking (
        tracking_id integer NOT NULL,
        user_id integer NOT NULL,
        goal_id integer,
        height numeric(5,2),
        weight numeric(5,2),
        recorded_date timestamp without time zone DEFAULT now()
    );

    ALTER TABLE public.progress_tracking ALTER COLUMN tracking_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.progress_tracking_tracking_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    CREATE TABLE public.users (
        user_id integer NOT NULL,
        username character varying(50) NOT NULL,
        password character varying(255) NOT NULL,
        created_at timestamp without time zone DEFAULT now()
    );

    ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.users_user_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    CREATE TABLE public.workout_exercises (
        workout_id integer NOT NULL,
        exercise_id integer NOT NULL,
        exercise_duration integer NOT NULL
    );

    CREATE TABLE public.workouts (
        workout_id integer NOT NULL,
        user_id integer NOT NULL,
        duration integer NOT NULL,
        workout_date timestamp without time zone DEFAULT now()
    );

    ALTER TABLE public.workouts ALTER COLUMN workout_id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME public.workouts_workout_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
    );

    ALTER TABLE ONLY public.exercises ADD CONSTRAINT exercises_pkey PRIMARY KEY (exercise_id);
    ALTER TABLE ONLY public.food ADD CONSTRAINT food_pkey PRIMARY KEY (food_id);
    ALTER TABLE ONLY public.goals ADD CONSTRAINT goals_pkey PRIMARY KEY (goal_id);
    ALTER TABLE ONLY public.meal_foods ADD CONSTRAINT meal_foods_pkey PRIMARY KEY (meal_id, food_id);
    ALTER TABLE ONLY public.meals ADD CONSTRAINT meals_pkey PRIMARY KEY (meal_id);
    ALTER TABLE ONLY public.progress_tracking ADD CONSTRAINT progress_tracking_pkey PRIMARY KEY (tracking_id);
    ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);
    ALTER TABLE ONLY public.users ADD CONSTRAINT users_username_key UNIQUE (username);
    ALTER TABLE ONLY public.workout_exercises ADD CONSTRAINT workout_exercises_pkey PRIMARY KEY (workout_id, exercise_id);
    ALTER TABLE ONLY public.workouts ADD CONSTRAINT workouts_pkey PRIMARY KEY (workout_id);
    ALTER TABLE ONLY public.goals ADD CONSTRAINT goals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
    ALTER TABLE ONLY public.meal_foods ADD CONSTRAINT meal_foods_food_id_fkey FOREIGN KEY (food_id) REFERENCES public.food(food_id) ON DELETE CASCADE;
    ALTER TABLE ONLY public.meal_foods ADD CONSTRAINT meal_foods_meal_id_fkey FOREIGN KEY (meal_id) REFERENCES public.meals(meal_id) ON DELETE CASCADE;
    ALTER TABLE ONLY public.meals ADD CONSTRAINT meals_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
    ALTER TABLE ONLY public.progress_tracking ADD CONSTRAINT progress_tracking_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(goal_id) ON DELETE SET NULL;
    ALTER TABLE ONLY public.progress_tracking ADD CONSTRAINT progress_tracking_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;
    ALTER TABLE ONLY public.workout_exercises ADD CONSTRAINT workout_exercises_exercise_id_fkey FOREIGN KEY (exercise_id) REFERENCES public.exercises(exercise_id) ON DELETE CASCADE;
    ALTER TABLE ONLY public.workout_exercises ADD CONSTRAINT workout_exercises_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES public.workouts(workout_id) ON DELETE CASCADE;
    ALTER TABLE ONLY public.workouts ADD CONSTRAINT workouts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: nutritiontrax
type: Opaque
stringData:
  POSTGRES_PASSWORD: "Meatball2023!"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: nutritiontrax
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: nutritiontrax
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          value: nutrition_user
        - name: POSTGRES_DB
          value: nutrition_dev
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
        - name: init-sql
          mountPath: /docker-entrypoint-initdb.d/01-init.sql
          subPath: init.sql
        - name: schema-sql
          mountPath: /docker-entrypoint-initdb.d/02-schema.sql
          subPath: schema.sql
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-sql
        configMap:
          name: postgres-init
      - name: schema-sql
        configMap:
          name: postgres-schema

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: nutritiontrax
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: nutritiontrax
data:
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: nutrition_user
  DB_NAME: nutrition_dev
  FRONTEND_URL: "https://nutrition-tracker.discovery.cs.vt.edu"
  SECURE_COOKIES: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: nutritiontrax
type: Opaque
stringData:
  DB_PASSWORD: "Meatball2023!"
  SECRET_KEY: "super-secret-key-change-in-production"
  JWT_SECRET: "jwt-secret-key-change-in-production"
  USDA_KEY: "91EtLz7zkCFgpJc7IC8s1gjfd4c8e8lbPXh60vqb"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: nutritiontrax
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: quinn341/nutrition-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: nutritiontrax
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
  - port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-nginx-config
  namespace: nutritiontrax
data:
  default.conf: |
    upstream gunicorn_backend {
        server backend:5000;
        keepalive 32;
    }

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        client_max_body_size 20M;

        location / {
            try_files $uri /index.html;
            expires 1h;
            add_header Cache-Control "public, immutable";
        }

        location /api/ {
            proxy_pass http://gunicorn_backend;
            proxy_http_version 1.1;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection "";
            
            proxy_connect_timeout 60s;
            proxy_send_timeout 120s;
            proxy_read_timeout 120s;
            
            proxy_buffering on;
            proxy_buffer_size 4k;
            proxy_buffers 8 4k;
            proxy_busy_buffers_size 8k;
            proxy_request_buffering off;
        }

        location /health {
            proxy_pass http://gunicorn_backend;
            proxy_http_version 1.1;
            access_log off;
        }

        location ~ /\. {
            deny all;
            access_log off;
            log_not_found off;
        }

        error_page 404 /index.html;
        error_page 500 502 503 504 /50x.html;
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: nutritiontrax
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: quinn341/nutrition-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"
      volumes:
      - name: nginx-config
        configMap:
          name: frontend-nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: nutritiontrax
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nutrition-ingress
  namespace: nutritiontrax
  annotations:
    traefik.ingress.kubernetes.io/router.middlewares: ""
spec:
  rules:
  - host: nutrition-tracker.discovery.cs.vt.edu
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
      - path: /api/
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000
